### ISSUE TITLE
[test] Need performance test

### ISSUE THREAD

**Issue by II11II** [Fennec-Framework/fennec#6]

**Comment by maks** [comment]
@akram-95 thanks for publishing the framework and doing the benchmarking, its great to see more people using Isolates for Dart serverside.

I do have a concern about the benchmark numbers you got, I would have expected a significant increase in throughput when you go from 1 to 10 threads, after all that's the whole point of doing multithreaded http serving, that you can have your Dart http server utilise all available cores on the machine. Note for instance the example in the benchmarks when this ServerSocket sharing feature [was first announced for Dart](https://groups.google.com/a/dartlang.org/g/misc/c/G9wYnvSG0UQ/m/bnm2vwZsQYwJ).
